### ISSUE TITLE
pep257 has been renamed to pydocstyle

### ISSUE THREAD

**Issue by smsrkr** [SublimeLinter/SublimeLinter-pep257#10]
shouldn't this plugin be updated to account for that?
otherwise `pip install pep257` actually installs pydocstyle, and subsequently SL3 gives out this unsightly error:
```
SublimeLinter: WARNING: import of pep257 module in pep257 failed, linter will not work with python 3 code 
```
Three solutions:

1. update this plugin.
2. in the SL3 dev guide, explicitly mention to install pep257 as `pip pep257==0.7.0` which seems to be the latest version that installs a `pep257.py`.<br>
  (The [dev.ref.](http://www.sublimelinter.com/en/latest/creating_a_linter.html#coding-guidelines) points to a url that will install pydocstyle)
3. create a copy of `pythondir\Lib\site-packages\pydocstyle.py` as `pep257.py` !

**Comment by FichteFoll** [comment]
I just installed pep257 version 0.7.0 with `pip install pep257`, so that appears to be working (now?).

**Comment by smsrkr** [comment]
indeed.

**Comment by smsrkr** [comment]
indeed.
