### ISSUE TITLE
Question: Can you help me understand why my tests are failing?

### ISSUE THREAD

**Issue by benedfit** [SublimeLinter/SublimeLinter-pep257#8]
https://github.com/benedfit/SublimeLinter-contrib-jade-lint Is currently failing with:

```
0.07s$ pep257 . --ignore=D202
./linter.py:16 in public class `JadeLint`:
        D211: No blank lines allowed before class docstring (found 1)
```

However when I remove the blank line, I then get an error telling me I need a blank line. Can you help me understand what I'm doing wrong, as I'm a Python noob?

**Comment by grotewold** [comment]
Not stupid at all. Looks like pep257 changed how `ignore` works. Used to append our ignores to the list of default rules. I'm working on adding the `--add-ignore` pep257 config. This will make D203 ignored by default. Until then, you can add `add-` before `ignore` in your `.sublimelinterrc` and `.travis.yml`. this should fix your issues until pep257 is fixed as well.

**Comment by benedfit** [comment]
Do you mind checking https://github.com/benedfit/SublimeLinter-contrib-jade-lint/commit/b08fc3b38aac170532979320caeb4918392efd37, as it doesn't seem to have solved the problem?

**Comment by benedfit** [comment]
This is now resolved
