### ISSUE TITLE
Warnings vs Errors

### ISSUE THREAD

**Issue by aristidesfl** [SublimeLinter/SublimeLinter-pep257#9]
Some rules are marked as warnings and some as errors.
Is this because some rules are more important then others?
If it is not breaking code, shouldn't it always be marked as a warning?

**Comment by nfvs** [comment]
Can you paste an example of an error here? There should be only warnings, are you sure it's not some other plugin marking them as errors?

**Comment by aristidesfl** [comment]
![screen shot 2015-12-02 at 20 52 58](https://cloud.githubusercontent.com/assets/208149/11542228/bc2041bc-9936-11e5-8f06-212ace33c010.png)

I see, so maybe the "too many blank lines" comes from pep8?
I saw D102 thought it was it, but it refers to other warning in the same line right?

**Comment by nfvs** [comment]
Too many blank lines is pep8 not pep257, pep257 is only about docstrings.
